### certificate get enrollment info
GET http://localhost:8082/certificate/enrollment-info
Accept: application/json
Authorization: {{token}}

> {%
    client.global.set("commonName", response.body.commonName);
    client.global.set("countryName", response.body.countryName);
    client.global.set("organizationName", response.body.organizationName);
    client.global.set("organizationIdentifier", response.body.organizationIdentifier);
%}

### certificate enrollment process

POST http://localhost:8082/certificate/send-enrollment
Accept: application/json
Content-Type: application/json
Authorization: {{token}}

{
  "commonName": "{{commonName}}",
  "countryName": "{{countryName}}",
  "organizationIdentifier": "{{organizationIdentifier}}",
  "organizationName": "{{organizationName}}"
}

> {%
    client.global.set("certReferenceNumber", response.body.referenceNumber);
%}

### certificate enrollment process status
GET http://localhost:8082/certificate/enrollment-status/{{certReferenceNumber}}
Accept: application/json
Authorization: {{token}}

> {%
    client.global.set("certificateSerialNumber", response.body.certificateSerialNumber);
%}

### certificate metadata list query

POST http://localhost:8082/certificate/certListMetadata
Accept: application/json
Content-Type: application/json
Authorization: {{token}}

{
  "certificateSerialNumber": "{{certificateSerialNumber}}",
  "name" : "",
  "expiresAfter" : ""
}

### certificate list query

POST http://localhost:8082/certificate/retrieve
Accept: application/json
Content-Type: application/json
Authorization: {{token}}

{
  "certificateSerialNumbers": ["{{certificateSerialNumber}}"]
}

### revoke certificate

POST http://localhost:8082/certificate/revoke/{{certificateSerialNumber}}
Accept: application/json
Content-Type: application/json
Authorization: {{token}}

{
  "revocationReason": "Superseded"
}